// This file was generated by gir (e48471c+) from gir-files (???)
// DO NOT EDIT

use ffi;
use glib::translate::*;

bitflags! {
    pub flags PtyFlags: u32 {
        const PTY_NO_LASTLOG = 1,
        const PTY_NO_UTMP = 2,
        const PTY_NO_WTMP = 4,
        const PTY_NO_HELPER = 8,
        const PTY_NO_FALLBACK = 16,
        const PTY_DEFAULT = 0,
    }
}

#[doc(hidden)]
impl ToGlib for PtyFlags {
    type GlibType = ffi::VtePtyFlags;

    fn to_glib(&self) -> ffi::VtePtyFlags {
        ffi::VtePtyFlags::from_bits_truncate(self.bits())
    }
}

#[doc(hidden)]
impl FromGlib<ffi::VtePtyFlags> for PtyFlags {
    fn from_glib(value: ffi::VtePtyFlags) -> PtyFlags {
        skip_assert_initialized!();
        PtyFlags::from_bits_truncate(value.bits())
    }
}

