// This file was generated by gir (24767f3+) from gir-files (???)
// DO NOT EDIT

use Error;
use ffi;
use glib::translate::*;
use std::ptr;

glib_wrapper! {
    pub struct Regex(Shared<ffi::VteRegex>);

    match fn {
        ref => |ptr| ffi::vte_regex_ref(ptr),
        unref => |_ptr| (),
    }
}

impl Regex {
    //pub fn new_for_match(pattern: &str, pattern_length: /*Unimplemented*/Fundamental: SSize, flags: u32) -> Result<Regex, Error> {
    //    unsafe { TODO: call ffi::vte_regex_new_for_match() }
    //}

    //pub fn new_for_search(pattern: &str, pattern_length: /*Unimplemented*/Fundamental: SSize, flags: u32) -> Result<Regex, Error> {
    //    unsafe { TODO: call ffi::vte_regex_new_for_search() }
    //}

    pub fn jit(&self, flags: u32) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::vte_regex_jit(self.to_glib_none().0, flags, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }
}
